import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const img = "/public/images/";
const phone = "010-9730-4719";
const casesPath = path.join(root, "content", "cases.json");
const cases = fs.existsSync(casesPath) ? JSON.parse(fs.readFileSync(casesPath, "utf8")) : [];
const guidesPath = path.join(root,"content","guides.json");
const guides = fs.existsSync(guidesPath) ? JSON.parse(fs.readFileSync(guidesPath,"utf8")) : [];
const publishedGuides = guides.filter((g)=>g.status === "published");
const publicCases = cases.filter((c)=>c.status === "published" || c.status === "example");
fs.mkdirSync(path.join(root,"content"),{recursive:true});
const nav=(on)=>`<header><div class="head"><a class="logo" href="/"><span>⌂</span><b>청년홈케어</b></a><nav class="pc"><a class="${on==='home'?'on':''}" href="/">홈</a><a href="/about/">청년홈케어 소개</a><a href="/services/">종합청소</a><a href="/home-care/">홈클리닝</a><a class="${on==='cases'?'on':''}" href="/cases/">시공사례</a><a class="${on==='guide'?'on':''}" href="/guide/">청소정보</a><a href="/contact/">상담문의</a></nav><a class="call" href="tel:01097304719">전화상담 ${phone}</a><button class="hamb" aria-controls="mobile" aria-expanded="false">☰</button></div><nav id="mobile" class="mobile"><a href="/">홈</a><a href="/about/">청년홈케어 소개</a><a href="/services/">종합청소</a><a href="/home-care/">홈클리닝</a><a class="${on==='cases'?'on':''}" href="/cases/">시공사례</a><a class="${on==='guide'?'on':''}" href="/guide/">청소정보</a><a href="/contact/">상담문의</a></nav></header>`;
const footer=()=>`<footer><div class="wrap foot"><div><a class="logo" href="/"><span>⌂</span><b>청년홈케어</b></a><p>서울·경기·인천 전 지역 기업·상가 종합청소와 홈클리닝 전문 서비스입니다. 사업자 정보와 상세 주소는 추후 입력합니다.</p></div><div><a href="/about/">청년홈케어 소개</a><a href="/services/">종합청소</a><a href="/home-care/">홈클리닝</a><a href="/cases/">시공사례</a><a href="/guide/">청소정보</a></div><div><a href="tel:01097304719">${phone}</a><a href="mailto:wh638654@naver.com">wh638654@naver.com</a><a href="/privacy/">개인정보처리방침</a></div></div></footer><div class="bottom"><a href="tel:01097304719">전화상담</a><a href="/contact/">무료 견적</a></div><script src="/assets/site.js" defer></script>`;
const page=({on,title,desc,canonical,body,image=""})=>`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><meta name="description" content="${desc}"><link rel="canonical" href="https://example.com${canonical}"><meta property="og:title" content="${title}"><meta property="og:description" content="${desc}">${image?`<meta property="og:image" content="https://example.com${image}">`:""}<link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/assets/styles.css"></head><body class="${on}-page content-page"><a class="skip" href="#main">본문 바로가기</a>${nav(on)}<main id="main">${body}</main>${footer()}</body></html>`;
fs.mkdirSync(path.join(root,"cases"),{recursive:true});
fs.writeFileSync(path.join(root,"cases","index.html"),page({on:"cases",title:"시공사례 | 청년홈케어 작업현장",desc:"서울·경기·인천에서 진행한 청년홈케어의 다양한 청소 현장을 사진과 간단한 작업설명으로 소개합니다.",canonical:"/cases/",body:`<section class="pagehero content-hero board-hero"><div class="wrap"><p class="eyebrow">FIELD NOTES</p><h1>청년홈케어의 현장 이야기</h1><p>청년홈케어가 작업한 다양한 청소 현장을 사진과 함께 소개합니다.</p><a class="btn" href="/contact/">무료 견적문의</a></div></section><section class="sec"><div class="wrap">${publicCases.length?`<div class="case-board-grid">${publicCases.map((c)=>`<a class="case board-card" href="/cases/${c.slug}/"><img src="${c.images[0]}" alt="${c.title} 대표 현장사진" loading="lazy"><span>${c.status==='example'?'예시 구성':c.service}</span><small>${c.service} · ${c.region}</small><h3>${c.title}</h3><p>${c.summary}</p><time>${c.publishedAt}</time><b>자세히 보기</b></a>`).join("")}</div>`:`<p class="empty empty-state">청년홈케어의 실제 작업자료를 준비하고 있습니다.</p>`}</div></section>`}));
for(const c of publicCases){
  fs.mkdirSync(path.join(root,"cases",c.slug),{recursive:true});
  const photos=c.images.slice(0,2);
  const serviceButton=c.relatedService?`<a class="btn ghost" href="${c.relatedService}">${c.service} 서비스 자세히 보기</a>`:"";
  const breadcrumb=`<script type="application/ld+json">${JSON.stringify({"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"홈",item:"https://example.com/"},{"@type":"ListItem",position:2,name:"시공사례",item:"https://example.com/cases/"},{"@type":"ListItem",position:3,name:c.title,item:`https://example.com/cases/${c.slug}/`}]})}</script>`;
  fs.writeFileSync(path.join(root,"cases",c.slug,"index.html"),page({on:"cases",title:`${c.title} | 청년홈케어 시공사례`,desc:`${c.region} ${c.service} 현장을 사진과 간단한 작업설명으로 소개합니다.`,canonical:`/cases/${c.slug}/`,image:photos[0],body:`${breadcrumb}<section class="sec case-detail board-detail"><div class="wrap narrow"><a class="backlink" href="/cases/">← 시공사례 목록으로</a><p class="eyebrow">홈 &gt; 시공사례 &gt; ${c.title}</p><h1>${c.title}</h1>${c.status==='example'?`<p class="notice">서비스 이해를 돕기 위한 예시 구성입니다. 실제 현장자료가 준비되면 실제 게시물로 교체합니다.</p>`:""}<dl class="meta-grid board-meta"><div><dt>서비스 종류</dt><dd>${c.service}</dd></div><div><dt>작업지역</dt><dd>${c.region}</dd></div><div><dt>작성일</dt><dd>${c.publishedAt}</dd></div></dl><div class="case-photo-grid photo-count-${photos.length}">${photos.map((src,i)=>`<figure><img src="${src}" alt="${c.title} 현장사진 ${i+1}" loading="lazy"><figcaption>${c.imageCaptions?.[i]||'현장사진'}</figcaption></figure>`).join("")}</div><h2>현장 작업내용</h2>${c.description.map((p)=>`<p>${p}</p>`).join("")}<div class="related-box board-cta"><h2>비슷한 공간의 청소가 필요하신가요?</h2><p>현장사진과 필요한 청소내용을 보내주시면 상담을 도와드립니다.</p><div>${serviceButton}<a class="btn" href="tel:01097304719">전화상담</a><a class="btn" href="/contact/">무료 견적문의</a></div></div></div></section>`}));
}
let home=fs.readFileSync(path.join(root,"index.html"),"utf8");
const recentCases=publicCases.filter((c)=>c.featured).slice(0,3);
const journal=`<section class="sec journal-sec"><div class="wrap"><div class="sh"><p>FIELD NOTES</p><h2>청년홈케어의 최근 작업현장</h2><span>최근 진행한 청소 현장을 사진과 함께 확인해 보세요.</span></div>${recentCases.length?`<div class="cases journal-grid case-board-grid home-case-board">${recentCases.map((c)=>`<a class="case board-card" href="/cases/${c.slug}/"><img src="${c.images[0]}" alt="${c.title} 대표 현장사진"><span>${c.status==='example'?'예시 구성':c.service}</span><small>${c.service} · ${c.region}</small><h3>${c.title}</h3><p>${c.summary}</p><b>자세히 보기</b></a>`).join("")}</div>`:`<p class="empty empty-state">청년홈케어의 실제 작업자료를 준비하고 있습니다.</p>`}<p class="home-more"><a class="btn ghost" href="/cases/">시공사례 전체보기</a></p></div></section>`;
home=home.replace(/<section class="sec journal-sec">[\s\S]*?<\/section>/,journal);
fs.writeFileSync(path.join(root,"index.html"),home);
const urls=["/","/about/","/services/","/home-care/","/cases/",...publicCases.filter((c)=>c.status==="published").map((c)=>`/cases/${c.slug}/`),"/guide/",...publishedGuides.map((g)=>`/guide/${g.slug}/`),"/faq/","/contact/","/privacy/"];
fs.writeFileSync(path.join(root,"sitemap.xml"),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map((u)=>`  <url><loc>https://example.com${u}</loc></url>`).join("\n")}\n</urlset>\n`);
console.log(`Generated ${publicCases.length} board case pages. Guide pages were left unchanged.`);
