import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const img = "/public/images/";
const phone = "010-9730-4719";
const cases = [
 {status:"example", slug:"example-floor-wax", title:"사무실 바닥 세척 및 왁스코팅 예시", category:"floor", categoryLabel:"바닥·왁스", service:"바닥·왁스코팅", region:"서울 강남구", spaceType:"사무실", summary:"보행이 많은 사무실 바닥의 광택 저하와 오염 누적을 정리하는 예시 구성입니다.", workDate:"예시 구성", duration:"확인 필요", crew:"확인 필요", workScope:"사무실 공용 바닥, 출입 동선", coverImage:img+"journal-floor-wax-v1.png", beforeImage:img+"office-before-full-v4.png", afterImage:img+"office-after-full-v4.png", relatedService:"/services/floor-wax/", relatedGuides:["floor-cleaning-wax-difference"], request:"바닥의 잔얼룩과 광택 저하로 공간이 어두워 보이는 상황을 가정한 예시입니다.", before:"의자 이동 자국, 보행 동선 얼룩, 기존 광택 저하가 있는 상태를 기준으로 구성했습니다.", plan:["현장 동선과 바닥 소재 확인", "먼지와 이물질 제거", "바닥 세척 후 건조 상태 확인", "왁스코팅 가능 범위 상담", "마감 후 주요 구역 점검"], result:"바닥 표면의 흐릿함을 줄이고, 사무실 첫인상이 더 정돈되어 보이도록 관리하는 흐름을 보여줍니다."},
 {status:"example", slug:"example-restroom", title:"상가 화장실 위생공간 청소 예시", category:"restroom", categoryLabel:"화장실", service:"화장실청소", region:"인천 연수구", spaceType:"상가 화장실", summary:"물때와 냄새 원인을 중심으로 세면대, 바닥, 배수구 주변을 점검하는 예시 구성입니다.", workDate:"예시 구성", duration:"확인 필요", crew:"확인 필요", workScope:"세면대, 변기, 바닥, 배수구 주변", coverImage:img+"journal-restroom-v1.png", beforeImage:img+"restroom-before-full-v4.png", afterImage:img+"restroom-after-full-v4.png", relatedService:"/services/restroom/", relatedGuides:["restroom-odor-after-cleaning"], request:"청소 후에도 냄새가 남거나 바닥 물때가 반복되는 상황을 가정했습니다.", before:"배수구 주변 냄새, 바닥 줄눈 오염, 세면대 물때가 누적된 공간을 기준으로 구성했습니다.", plan:["환기와 배수 상태 확인", "세면대와 수전 주변 세척", "바닥과 줄눈 오염 정리", "배수구 주변 관리", "마무리 냄새 확인"], result:"물때와 냄새 원인을 구역별로 나누어 확인하고, 반복 관리가 필요한 부분을 안내하는 흐름입니다."},
 {status:"example", slug:"example-aircon", title:"사무실 에어컨 필터·송풍구 청소 예시", category:"aircon", categoryLabel:"에어컨", service:"에어컨청소", region:"서울 마포구", spaceType:"사무실", summary:"필터 먼지와 송풍구 냄새를 중심으로 점검하는 에어컨청소 예시 구성입니다.", workDate:"예시 구성", duration:"확인 필요", crew:"확인 필요", workScope:"필터, 송풍구, 외관, 주변 정리", coverImage:img+"journal-aircon-v1.png", beforeImage:img+"aircon-before-full-v4.png", afterImage:img+"aircon-after-full-v4.png", relatedService:"/services/aircon/", relatedGuides:["aircon-filter-disassembly-difference"], request:"가동 전 냄새와 필터 먼지가 걱정되는 상황을 가정한 예시입니다.", before:"필터에 먼지가 쌓이고 송풍구 주변에 오염이 보이는 상태를 기준으로 구성했습니다.", plan:["전원과 작업 안전 확인", "필터 분리 가능 범위 확인", "필터 먼지 제거", "송풍구와 외관 관리", "건조와 작동 상태 확인"], result:"사용 빈도와 오염 정도에 따라 필터청소와 분해청소 상담 범위를 구분해 안내합니다."}
];

const guides = [
 {status:"published", slug:"cleaning-estimate-criteria", category:"prep", categoryLabel:"청소 준비·이용안내", title:"청소 견적은 어떤 기준으로 결정될까요?", summary:"면적만이 아니라 오염 정도, 작업 범위, 장비 사용, 일정 조건을 함께 봐야 견적이 달라집니다.", coverImage:img+"services-hero-comprehensive-v1.webp", minutes:4, date:"2026-10-04", relatedService:"/contact/", relatedCases:["example-floor-wax"], sections:["견적은 면적 하나로 정해지기보다 공간의 용도, 오염 정도, 작업 높이, 장비 진입 조건, 작업 시간대가 함께 반영됩니다.","사진 상담을 받을 때는 전체 공간 사진, 오염이 심한 부분, 물과 전기 사용 가능 여부, 주차와 출입 조건을 함께 보내주면 좋습니다.","직접 준비할 것은 귀중품 보관, 파손 위험 물품 이동, 작업 동선 확보입니다. 무거운 집기 이동이 필요한 경우에는 상담 때 미리 알려주세요.","전문 장비가 필요한 바닥 세척, 고소 유리창, 에어컨 분해, 강한 기름때 작업은 현장 확인 후 가능 범위를 안내받는 것이 안전합니다."]},
 {status:"published", slug:"photo-estimate-guide", category:"prep", categoryLabel:"청소 준비·이용안내", title:"현장사진만으로 청소 견적을 받을 수 있나요?", summary:"사진만으로 1차 상담은 가능하지만 최종 범위는 현장 조건에 따라 달라질 수 있습니다.", coverImage:img+"homecare-hero-clean-v1.webp", minutes:3, date:"2026-10-04", relatedService:"/contact/", relatedCases:["example-restroom"], sections:["현장사진은 상담을 빠르게 시작하는 데 큰 도움이 됩니다. 다만 사진에 보이지 않는 냄새, 소재 손상, 물 사용 조건은 추가 확인이 필요합니다.","공간 전체가 보이는 사진, 오염 부위 근접 사진, 출입구와 작업 동선, 전기와 수도 위치를 함께 보내면 상담 정확도가 높아집니다.","사진 견적은 작업 가능 범위와 예상 준비사항을 안내하는 단계로 보고, 현장 상황에 따라 작업 방식이나 일정이 조정될 수 있습니다.","무리하게 확정 가격을 약속하기보다 확인이 필요한 항목을 투명하게 안내하는 업체를 선택하는 것이 좋습니다."]},
 {status:"published", slug:"choosing-cleaning-company", category:"prep", categoryLabel:"청소 준비·이용안내", title:"청소업체를 선택할 때 확인해야 할 기준", summary:"작업 범위, 사진 상담 방식, 사후 확인 절차, 과장 표현 여부를 함께 확인하세요.", coverImage:img+"about-professional-team.svg", minutes:4, date:"2026-10-04", relatedService:"/about/", relatedCases:[], sections:["청소업체를 고를 때는 가격만 비교하기보다 어떤 구역을 어떤 순서로 작업하는지 설명할 수 있는지 확인해야 합니다.","모든 오염을 완전히 제거한다고 단정하거나 현장 확인 없이 과도하게 낮은 가격을 제시하는 경우에는 작업 범위를 다시 확인하는 편이 좋습니다.","작업 전후 확인 절차, 파손 위험 물품 안내, 작업 불가 항목 설명이 있는지 살펴보세요.","청년홈케어는 현장 사진과 공간 정보를 바탕으로 필요한 작업 범위를 먼저 상담하고, 확인이 필요한 정보는 임의로 단정하지 않습니다."]},
 {status:"published", slug:"office-regular-cleaning-cycle", category:"office", categoryLabel:"사무실·상가", title:"사무실 정기청소는 얼마나 자주 해야 할까요?", summary:"이용 인원, 바닥 소재, 화장실 사용량, 고객 방문 여부에 따라 주기가 달라집니다.", coverImage:img+"services-regular-cleaning-v1.webp", minutes:4, date:"2026-10-04", relatedService:"/services/regular/", relatedCases:["example-floor-wax"], sections:["사무실 정기청소 주기는 공간을 사용하는 인원과 오염이 쌓이는 속도에 따라 달라집니다. 직원 수가 많거나 고객 방문이 잦은 공간은 관리 주기를 짧게 잡는 편이 좋습니다.","기본 관리는 바닥 먼지, 쓰레기, 책상 주변, 탕비실, 화장실 상태를 중심으로 봅니다. 바닥 광택이나 카펫 먼지처럼 누적되는 항목은 별도 주기로 계획합니다.","직접 관리할 때는 매일 쓰레기와 음식물 냄새를 먼저 줄이고, 주 1회 이상 바닥과 공용부를 확인하는 것이 도움이 됩니다.","정기청소 상담 시에는 공간 면적, 근무 인원, 원하는 요일과 시간, 우선 관리 구역을 알려주시면 좋습니다."]},
 {status:"published", slug:"office-cleaning-scope", category:"office", categoryLabel:"사무실·상가", title:"상가·사무실청소의 기본 작업범위", summary:"바닥, 집기, 유리, 출입 동선, 공용부를 중심으로 공간에 맞춰 작업 범위를 정합니다.", coverImage:img+"services-office-shop-v1.webp", minutes:4, date:"2026-10-04", relatedService:"/services/office/", relatedCases:["example-floor-wax"], sections:["상가와 사무실은 고객과 직원이 함께 사용하는 공간이므로 첫인상과 동선 관리가 중요합니다.","기본 범위는 바닥 먼지와 얼룩, 출입문 주변, 상담실이나 회의실, 탕비실, 유리와 손잡이처럼 자주 만지는 부분입니다.","직접 청소할 때는 전자기기 주변 물 사용을 피하고, 바닥 소재에 맞지 않는 세제를 쓰지 않는 것이 중요합니다.","전문 작업이 필요한 경우는 바닥 왁스코팅, 대형 유리, 높은 곳 먼지, 장기간 누적된 오염처럼 일반 도구로 정리가 어려운 상황입니다."]},
 {status:"published", slug:"floor-cleaning-wax-difference", category:"floor", categoryLabel:"바닥·왁스", title:"바닥청소와 왁스코팅은 무엇이 다를까요?", summary:"바닥청소는 오염 제거, 왁스코팅은 표면 보호와 광택 관리에 초점이 있습니다.", coverImage:img+"services-floor-wax-v1.webp", minutes:5, date:"2026-10-04", relatedService:"/services/floor-wax/", relatedCases:["example-floor-wax"], sections:["바닥청소는 먼지, 얼룩, 끈적임처럼 표면에 남은 오염을 정리하는 작업입니다. 왁스코팅은 세척 후 표면을 보호하고 광택을 더하는 관리 방식입니다.","왁스코팅이 항상 필요한 것은 아닙니다. 바닥 소재, 기존 코팅 상태, 보행량, 미끄럼 위험을 확인한 뒤 결정해야 합니다.","직접 관리할 때는 강한 세제를 반복 사용하거나 물을 오래 남겨두지 않는 것이 좋습니다. 소재에 맞지 않는 방법은 변색이나 들뜸을 만들 수 있습니다.","전문 상담에는 바닥 소재, 면적, 기존 코팅 여부, 광택 저하 사진, 작업 가능한 시간을 알려주시면 도움이 됩니다."]},
 {status:"draft", slug:"restroom-odor-after-cleaning", category:"restroom", categoryLabel:"화장실·주방", title:"화장실 냄새가 청소 후에도 남는 이유"},
 {status:"draft", slug:"kitchen-hood-grease-care", category:"restroom", categoryLabel:"화장실·주방", title:"주방 후드와 벽면 기름때 관리방법"},
 {status:"draft", slug:"aircon-filter-disassembly-difference", category:"window-aircon", categoryLabel:"유리창·에어컨", title:"에어컨 필터청소와 분해청소의 차이"},
 {status:"draft", slug:"move-in-moving-cleaning-difference", category:"move", categoryLabel:"입주·이사·준공", title:"입주청소와 이사청소의 차이"},
 {status:"draft", slug:"move-in-cleaning-checklist", category:"move", categoryLabel:"입주·이사·준공", title:"입주청소 완료 후 확인해야 할 점검표"},
 {status:"draft", slug:"fabric-cleaning-timing", category:"fabric", categoryLabel:"소파·매트리스·카펫", title:"소파와 매트리스청소가 필요한 시기"}
];

fs.mkdirSync(path.join(root,"content"), {recursive:true});
fs.writeFileSync(path.join(root,"content","cases.json"), JSON.stringify(cases,null,2));
fs.writeFileSync(path.join(root,"content","guides.json"), JSON.stringify(guides,null,2));

const nav=(on)=>`<header><div class="head"><a class="logo" href="/"><span>⌂</span><b>청년홈케어</b></a><nav class="pc"><a class="${on==='home'?'on':''}" href="/">홈</a><a href="/about/">청년홈케어 소개</a><a href="/services/">종합청소</a><a href="/home-care/">홈클리닝</a><a class="${on==='cases'?'on':''}" href="/cases/">시공사례</a><a class="${on==='guide'?'on':''}" href="/guide/">청소정보</a><a href="/contact/">상담문의</a></nav><a class="call" href="tel:01097304719">전화상담 ${phone}</a><button class="hamb" aria-controls="mobile" aria-expanded="false">☰</button></div><nav id="mobile" class="mobile"><a href="/">홈</a><a href="/about/">청년홈케어 소개</a><a href="/services/">종합청소</a><a href="/home-care/">홈클리닝</a><a class="${on==='cases'?'on':''}" href="/cases/">시공사례</a><a class="${on==='guide'?'on':''}" href="/guide/">청소정보</a><a href="/contact/">상담문의</a></nav></header>`;
const footer=()=>`<footer><div class="wrap foot"><div><a class="logo" href="/"><span>⌂</span><b>청년홈케어</b></a><p>서울·경기·인천 전 지역 기업·상가 종합청소와 홈클리닝 전문 서비스입니다. 사업자 정보와 상세 주소는 추후 입력합니다.</p></div><div><a href="/about/">청년홈케어 소개</a><a href="/services/">종합청소</a><a href="/home-care/">홈클리닝</a><a href="/cases/">시공사례</a><a href="/guide/">청소정보</a></div><div><a href="tel:01097304719">${phone}</a><a href="mailto:wh638654@naver.com">wh638654@naver.com</a><a href="/privacy/">개인정보처리방침</a></div></div></footer><div class="bottom"><a href="tel:01097304719">전화상담</a><a href="/contact/">무료 견적</a></div><script src="/assets/site.js" defer></script>`;
const page=(on,title,desc,body,extra="")=>`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><meta name="description" content="${desc}"><link rel="canonical" href="https://example.com/${on==='home'?'':on+'/'}"><meta property="og:title" content="${title}"><meta property="og:description" content="${desc}"><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/assets/styles.css">${extra}</head><body class="${on}-page content-page"><a class="skip" href="#main">본문 바로가기</a>${nav(on)}<main id="main">${body}</main>${footer()}</body></html>`;
const caseCats=[['all','전체'],['regular','정기청소'],['office','상가·사무실'],['floor','바닥·왁스'],['building','건물·계단'],['parking','주차장'],['restroom','화장실'],['window','유리창'],['kitchen','급식실·주방'],['special','특수청소'],['aircon','에어컨'],['move','입주·이사·준공'],['fabric','소파·매트리스·카펫']];
const guideCats=[['all','전체'],['prep','청소 준비·이용안내'],['office','사무실·상가'],['building','건물·공용공간'],['floor','바닥·왁스'],['restroom','화장실·주방'],['window-aircon','유리창·에어컨'],['move','입주·이사·준공'],['fabric','소파·매트리스·카펫']];
const publishedGuides=guides.filter(g=>g.status==='published');
const publicCases=cases.filter(c=>c.status==='published'||c.status==='example');
function filters(cats){return `<div class="filterbar" role="list">${cats.map(([k,v])=>`<button type="button" data-filter="${k}" class="${k==='all'?'active':''}">${v}</button>`).join("")}</div>`}
function filterScript(){return `<script>const buttons=[...document.querySelectorAll('[data-filter]')],cards=[...document.querySelectorAll('[data-category]')],empty=document.querySelector('.empty-state');function setFilter(k){buttons.forEach(b=>b.classList.toggle('active',b.dataset.filter===k));let shown=0;cards.forEach(c=>{const ok=k==='all'||c.dataset.category===k;c.hidden=!ok;if(ok)shown++;});if(empty)empty.hidden=shown!==0;const u=new URL(location);if(k==='all')u.searchParams.delete('category');else u.searchParams.set('category',k);history.replaceState(null,'',u)}buttons.forEach(b=>b.addEventListener('click',()=>setFilter(b.dataset.filter)));setFilter(new URL(location).searchParams.get('category')||'all');</script>`}

fs.rmSync(path.join(root,"cases"),{recursive:true,force:true}); fs.mkdirSync(path.join(root,"cases"),{recursive:true});
fs.writeFileSync(path.join(root,"cases","index.html"), page('cases','청년홈케어 시공사례 | 서울·경기·인천 종합청소','상가·사무실·건물·입주청소 등 청년홈케어의 작업과정과 청소 전후 시공사례를 확인해 보세요.',`<section class="pagehero content-hero"><div class="wrap"><p class="eyebrow">FIELD JOURNAL</p><h1>결과로 보여드리는 청년홈케어의 작업 기록</h1><p>현장의 문제와 작업과정, 청소 전후의 변화를 확인해 보세요.</p><a class="btn" href="/contact/">무료 견적문의</a></div></section><section class="sec"><div class="wrap">${filters(caseCats)}<div class="cases journal-grid content-grid">${publicCases.map(c=>`<a class="case content-card" data-category="${c.category}" href="/cases/${c.slug}/"><img src="${c.coverImage}" alt="${c.title} 대표 이미지" loading="lazy"><span>${c.status==='example'?'예시 구성 · 실제 자료 준비 중':c.service}</span><h3>${c.title}</h3><p>${c.region} · ${c.spaceType}</p><small>${c.summary}</small><b>상세보기</b></a>`).join('')}</div><p class="empty empty-state" hidden>선택한 조건의 시공사례가 아직 준비 중입니다. 필요한 서비스는 상담으로 먼저 문의해 주세요.</p></div></section>${filterScript()}`));
for(const c of publicCases){fs.mkdirSync(path.join(root,"cases",c.slug),{recursive:true});const relGuides=publishedGuides.filter(g=>c.relatedGuides.includes(g.slug));fs.writeFileSync(path.join(root,"cases",c.slug,"index.html"), page('cases',`${c.title} | 청년홈케어 시공사례`,`${c.service} 작업 과정과 전후 변화를 정리한 ${c.status==='example'?'예시 구성':'시공사례'}입니다.`,`<section class="sec case-detail"><div class="wrap narrow"><a class="backlink" href="/cases/">← 시공사례 목록으로</a><p class="eyebrow">홈 &gt; 시공사례 &gt; ${c.service}</p><h1>${c.title}</h1><p class="notice">${c.status==='example'?'서비스 이해를 돕기 위한 예시 구성입니다. 실제 고객 현장자료가 제공되면 실제 사례로 교체합니다.':''}</p><dl class="meta-grid"><div><dt>작업 지역</dt><dd>${c.region}</dd></div><div><dt>공간 종류</dt><dd>${c.spaceType}</dd></div><div><dt>서비스 종류</dt><dd>${c.service}</dd></div><div><dt>작업일</dt><dd>${c.workDate}</dd></div><div><dt>작업 범위</dt><dd>${c.workScope}</dd></div><div><dt>작업시간</dt><dd>${c.duration}</dd></div><div><dt>작업 인원</dt><dd>${c.crew}</dd></div></dl><h2>고객 요청사항</h2><p>${c.request}</p><h2>작업 전 상태</h2><p>${c.before}</p><div class="before-after"><figure><img src="${c.beforeImage}" alt="${c.title} 작업 전 예시 이미지"><figcaption>작업 전</figcaption></figure><figure><img src="${c.afterImage}" alt="${c.title} 작업 후 예시 이미지"><figcaption>작업 후</figcaption></figure></div><h2>작업 계획과 과정</h2><ol class="process-list">${c.plan.map(x=>`<li>${x}</li>`).join('')}</ol><h2>작업 결과</h2><p>${c.result}</p><div class="related-box"><a class="btn" href="${c.relatedService}">관련 서비스 자세히 보기</a>${relGuides.map(g=>`<a class="btn ghost" href="/guide/${g.slug}/">${g.title}</a>`).join('')}<a class="btn" href="/contact/">비슷한 작업 견적문의</a></div></div></section>`));}

fs.rmSync(path.join(root,"guide"),{recursive:true,force:true}); fs.mkdirSync(path.join(root,"guide"),{recursive:true});
fs.writeFileSync(path.join(root,"guide","index.html"), page('guide','청소정보 | 청년홈케어 청소가이드','사무실·상가·바닥·화장실·에어컨·입주청소 등 공간별 청소방법과 준비사항, 관리방법을 안내합니다.',`<section class="pagehero content-hero"><div class="wrap"><p class="eyebrow">CLEANING GUIDE</p><h1>공간을 깨끗하게 관리하는 실용적인 청소정보</h1><p>청소 준비사항부터 서비스 선택, 작업 후 관리방법까지 고객이 궁금해하는 내용을 알기 쉽게 안내합니다.</p><a class="btn" href="/contact/">무료 견적문의</a></div></section><section class="sec"><div class="wrap">${filters(guideCats)}<div class="cards content-grid">${publishedGuides.map(g=>`<a class="card content-card" data-category="${g.category}" href="/guide/${g.slug}/"><img src="${g.coverImage}" alt="${g.title} 설명 이미지" loading="lazy"><span>${g.categoryLabel}</span><b>${g.title}</b><p>${g.summary}</p><small>${g.date} · 약 ${g.minutes}분</small></a>`).join('')}</div><p class="empty empty-state" hidden>검색 조건에 맞는 청소정보가 아직 없습니다.</p></div></section>${filterScript()}`));
for(const g of publishedGuides){fs.mkdirSync(path.join(root,"guide",g.slug),{recursive:true});const relCases=publicCases.filter(c=>g.relatedCases.includes(c.slug));const toc=["핵심 요약","관리 방법","주의할 점","전문가 상담이 필요한 경우","견적에 필요한 정보"];fs.writeFileSync(path.join(root,"guide",g.slug,"index.html"), page('guide',`${g.title} | 청년홈케어 청소정보`,g.summary,`<section class="sec guide-detail"><div class="wrap narrow"><a class="backlink" href="/guide/">← 청소정보 목록으로</a><p class="eyebrow">홈 &gt; 청소정보 &gt; ${g.categoryLabel}</p><h1>${g.title}</h1><p class="lead">${g.summary}</p><p class="post-meta">${g.categoryLabel} · ${g.date} · 약 ${g.minutes}분</p><img class="detail-cover" src="${g.coverImage}" alt="${g.title} 대표 이미지"><details class="toc" open><summary>목차</summary><ol>${toc.map(t=>`<li><a href="#${t.replaceAll(' ','-')}">${t}</a></li>`).join('')}</ol></details><h2 id="핵심-요약">핵심 요약</h2><p>${g.sections[0]}</p><h2 id="관리-방법">관리 방법</h2><p>${g.sections[1]}</p><h2 id="주의할-점">주의할 점</h2><p>${g.sections[2]}</p><h2 id="전문가-상담이-필요한-경우">전문가 상담이 필요한 경우</h2><p>${g.sections[3]}</p><h2 id="견적에-필요한-정보">견적에 필요한 정보</h2><p>상담 시 공간 사진, 위치, 희망 일정, 우선 청소 구역, 물과 전기 사용 가능 여부를 알려주시면 작업 범위를 더 빠르게 확인할 수 있습니다.</p><div class="related-box"><a class="btn" href="${g.relatedService}">관련 서비스 알아보기</a>${relCases.map(c=>`<a class="btn ghost" href="/cases/${c.slug}/">${c.title}</a>`).join('')}<a class="btn" href="/contact/">무료 견적문의</a></div></div></section>`, `<script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"전문 청소 상담 전 무엇을 준비하면 좋나요?","acceptedAnswer":{"@type":"Answer","text":"공간 사진, 위치, 희망 일정, 청소가 필요한 구역, 물과 전기 사용 가능 여부를 준비하면 상담이 빠릅니다."}}]}</script>`));}

let home=fs.readFileSync(path.join(root,"index.html"),"utf8");
const journal=`<section class="sec journal-sec"><div class="wrap"><div class="sh"><p>FIELD JOURNAL</p><h2>결과로 보여드리는 청년홈케어의 작업 기록</h2><span>현재 공개된 항목은 실제 현장자료가 아닌 예시 구성입니다. 실제 자료가 준비되면 교체됩니다.</span></div><div class="cases journal-grid">${publicCases.slice(0,3).map(c=>`<a class="case" href="/cases/${c.slug}/"><img src="${c.coverImage}" alt="${c.title} 대표 이미지"><span>예시 구성</span><h3>${c.title}</h3><p>${c.region} · ${c.service}</p></a>`).join('')}</div><p class="home-more"><a class="btn ghost" href="/cases/">시공사례 전체보기</a></p></div></section>\n\n    <section class="sec guide-home-sec soft"><div class="wrap"><div class="sh"><p>CLEANING GUIDE</p><h2>청소 전에 알아두면 좋은 정보</h2><span>서비스 선택과 준비사항을 쉽게 확인할 수 있는 청소정보입니다.</span></div><div class="cards journal-grid">${publishedGuides.slice(0,3).map(g=>`<a class="card" href="/guide/${g.slug}/"><img src="${g.coverImage}" alt="${g.title} 설명 이미지"><span>${g.categoryLabel}</span><b>${g.title}</b><p>${g.summary}</p><small>${g.date}</small></a>`).join('')}</div><p class="home-more"><a class="btn ghost" href="/guide/">청소정보 전체보기</a></p></div></section>`;
home=home.replace(/<section class="sec journal-sec">[\s\S]*?<\/section>\s*<section class="sec standards soft">/, journal+"\n\n    <section class=\"sec standards soft\">");
fs.writeFileSync(path.join(root,"index.html"), home);

const urls=["/","/about/","/services/","/home-care/","/cases/",...publicCases.map(c=>`/cases/${c.slug}/`),"/guide/",...publishedGuides.map(g=>`/guide/${g.slug}/`),"/faq/","/contact/","/privacy/"];
fs.writeFileSync(path.join(root,"sitemap.xml"),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map(u=>`  <url><loc>https://example.com${u}</loc></url>`).join("\n")}\n</urlset>\n`);
console.log(`Generated ${publicCases.length} case pages and ${publishedGuides.length} guide pages.`);
